# Generated by Django 2.1 on 2019-07-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
