# Generated by Django 2.1 on 2019-07-23 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choose', models.CharField(choices=[('wt', 'waiting'), ('wa', 'working'), ('dn', 'done')], default='wt', max_length=15)),
                ('id_no', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('discription', models.TextField(blank=True, max_length=200)),
                ('created_date', models.DateField(default='2019-07-23')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id_no'],
            },
        ),
    ]
